import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {I,project,recoverPose,triangulate,norm,sub,center,median,eightPoint,sampson} from '../dist/engine/math.mjs';
import {solvePose} from '../dist/engine/sfm.mjs';
import {MAX_PHOTOS,canAdd,validateCount,intrinsics} from '../dist/policy.mjs';
const require=createRequire(import.meta.url),cv=require('../dist/vendor/opencv.js');
await new Promise(r=>cv.Mat?r():cv.onRuntimeInitialized=r);
const k={f:500,cx:319.5,cy:239.5},p1={R:I(),t:[0,0,0]},theta=0.12,p2={R:[Math.cos(theta),0,Math.sin(theta),0,1,0,-Math.sin(theta),0,Math.cos(theta)],t:[-0.7,0.02,0.03]};
let seed=43;const rng=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;};
const points=Array.from({length:160},()=>[(rng()-.5)*3,(rng()-.5)*2,4+rng()*5]);
const a=points.map(p=>project(p1,p,k).slice(0,2)),b=points.map(p=>project(p2,p,k).slice(0,2));
const noisy=b.map((p,i)=>i%5===0?[rng()*640,rng()*480]:p.map(x=>x+(rng()-.5)*.4));
const hit=recoverPose(cv,a,noisy,k,k);assert.ok(hit&&hit.points.length>=100,'RANSAC must recover geometry despite 20% bad matches');
const expected=norm(p2.t),ratios=hit.points.map(p=>norm(p.x)/norm(points[p.i]));assert.ok(Math.abs(median(ratios)-1/expected)<0.04);
const re=hit.p2.R.map((v,i)=>Math.abs(v-p2.R[i]));assert.ok(Math.max(...re)<0.015,`rotation error ${Math.max(...re)}`);
const solved=solvePose(cv,points,noisy,k);assert.ok(solved&&solved.inliers.length>=120);assert.ok(norm(sub(solved.pose.t,p2.t))<.03);
assert.equal(triangulate(p1,p1,a[0],a[0],k,k),null,'pure rotation / zero baseline cannot produce 3D');
for(let n=0;n<1000;n++)assert.equal(canAdd(n),true);assert.equal(canAdd(1000),false);assert.equal(canAdd(1001),false);validateCount(1000);assert.throws(()=>validateCount(1001));assert.throws(()=>validateCount(2));
const ki=intrinsics({width:1600,height:1200,focal35:26},26,true,800);assert.equal(ki.width,800);assert.ok(ki.f>590&&ki.f<610);
console.log(JSON.stringify({test:'geometry and limits',inliers:hit.points.length,rotationMaxError:Math.max(...re),poseTranslationError:norm(sub(solved.pose.t,p2.t)),maxPhotos:MAX_PHOTOS}));
